spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.Oracle10gDialect
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: scott 
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver
sri:
  map:
    form: register
    display: view
    up: update
    err: error
    ns: Register not Successfull-dev
    s: RegisterEntity Successfull-dev
    uns: Update Register not Successfull-dev
    us: Update RegisterEnt Successfull-dev